<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="article">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="meta" type="Meta"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="h"          type="xs:string"/>
          <xs:element name="p"          type="Inline"/>
          <xs:element name="code"       type="Code"/>
          <xs:element name="blockquote" type="Inline"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Meta">
    <xs:all>
      <xs:element name="title"     type="xs:string"/>
      <xs:element name="published" type="xs:date"/>
      <xs:element name="updated"   type="xs:date"/>
      <xs:element name="summary"   type="xs:string" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="Inline" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="i" type="xs:string"/>
      <xs:element name="m" type="xs:string"/>
      <xs:element name="a" type="Link"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="Link">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="href" type="xs:anyURI" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="Code">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>
