cabal-version:      2.4
name:               site
version:            0.1.0.0
build-type:         Simple

executable site
    main-is:          Main.hs
    hs-source-dirs:   app
    other-modules:    Main.Path
                    , Main.Path.Extra
    build-tool-depends: doctest:doctest
    build-depends:    base >=4 && <5
                    , containers
                    , exceptions
                    , filepath
                    , lucid2
                    , feed
                    , network-uri
                    , pandoc
                    , pandoc-types
                    , path
                    , shake
                    , sitemap-gen
                    , skylighting
                    , template-haskell
                    , text
                    , time
                    , transformers
    default-extensions: OverloadedStrings
                       , QuasiQuotes
                       , LambdaCase
    ghc-options:      -Wall
    default-language: Haskell2010
